name: Publish Splunk Application to Splunkbase

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.9'

      - name: Install Application Dependencies
        run: |
          make build

      - name: Package and Publish
        run: |
          make package
          SPLUNKBASE_CREDS="${{ secrets.SPLUNKBASE_CREDS }}" make publish
